### ISSUE TITLE
Compatibility with mtl-2.3 / transformers-0.6

### ISSUE THREAD

**Issue by sjakobi** [diagrams/diagrams-lib#358]
The latest `diagrams-lib` release fails to build with `transformers-0.6`:

```
$ cabal install diagrams-lib --constraint 'transformers >= 0.6' --allow-newer=diagrams-lib:mtl,newtype-generics:transformers,JuicyPixels:mtl

<...>

src/Diagrams/Util.hs:159:3: error:
    Ambiguous occurrence ‘hoistMaybe’
    It could refer to
       either ‘Control.Monad.Trans.Maybe.hoistMaybe’,
              imported from ‘Control.Monad.Trans.Maybe’ at src/Diagrams/Util.hs:41:1-42
           or ‘Diagrams.Util.hoistMaybe’,
              defined at src/Diagrams/Util.hs:242:1
    |
159 |   hoistMaybe $ config ^? lined . prefixed "package-db: "
    |   ^^^^^^^^^^

src/Diagrams/Util.hs:183:50: error:
    Ambiguous occurrence ‘hoistMaybe’
    It could refer to
       either ‘Control.Monad.Trans.Maybe.hoistMaybe’,
              imported from ‘Control.Monad.Trans.Maybe’ at src/Diagrams/Util.hs:41:1-42
           or ‘Diagrams.Util.hoistMaybe’,
              defined at src/Diagrams/Util.hs:242:1
    |
183 |     else maybeIO (getDirectoryContents path) >>= hoistMaybe . find isConf
    |                                                  ^^^^^^^^^^

cabal: Failed to build diagrams-lib-1.4.5.1.
```

The reason seems to be that `hoistMaybe` was added in `transformers-0.6.0.0`: https://hackage.haskell.org/package/transformers-0.6.0.4/changelog

**Comment by byorgey** [comment]
Thanks for the report, I'll get this updated soon.

**Comment by byorgey** [comment]
Uploaded to Hackage as `diagrams-lib-1.4.5.2`.  Sorry for the long delay!

**Comment by sjakobi** [comment]
No worries, @byorgey. :) Back when I opened this issue, I wouldn't have imagined that we'd still be waiting for a non-deprecated `mtl-2.3.*` release today!

**Comment by byorgey** [comment]
@sjakobi , indeed.   I was going to respond with an emoji but I couldn't figure out which one applied...
